### ISSUE TITLE
Logs spam the console and cannot be redirected

### ISSUE THREAD

**Issue by Dessix** [ZHaskell/zoovisitor#34]
Hello- I attempted to use this library for a CLI tool and had to make some questionable moves in order to reduce log pollution, as `zoo_set_log_stream` is not exposed by the API, and my naive-to-Haskell attempts to bind it to `/dev/null` led to segfaults.

My workaround was to set the log-level to `(unsafeCoerce @ZooKeeper.ZooLogLevel (0 :: CInt))` during initial connection attempts[^1], and run the connection attempt in a thread to allow manual timeout handling, then - upon seeing the state was `ZCONNECTED` [^2] or timeout being reached, return or fail.

Perhaps exposing the [`zoo_set_log_stream`](https://zookeeper.dpldocs.info/deimos.zookeeper.zookeeper.zoo_set_log_stream.html) API, or maybe providing an easy way to pipe them to a `TQueue` or similar would be helpful? Similarly, connect timeouts or retry attempt counts before throwing some sort of exception or return state would be nice.

P.S. I'm not clear of the exception handling model, but it seemed very unclear how to actually handle the results of a call without writing an FFI wrapper instead of doing the exception conversions on the fly. I didn't see any examples in the docs or tests that cleared this up, but it didn't seem worth opening another issue for, without further clarification.

[^1]: Which somehow worked despite this being apparently unsupported by the C library itself?
[^2]: Notably, state `999` (`ZNOTCONNECTED_STATE`) is not exposed by this API, and there's no exposed way beyond unsafe-coerce (or, in the other direction, parsing of `show`) to provide custom values to or extract the inner contents from either the state values or log levels.

**Comment by 4eUeP** [comment]
Thanks for your suggestions. So, you mean you want to disable logging totally, even the error log? In most cases, setting the log level to ERROR is OK.

> as zoo_set_log_stream is not exposed by the API

Support zoo_set_log_stream sounds reasonable.

> set the log-level to (unsafeCoerce @ZooKeeper.ZooLogLevel (0 :: CInt))

Yeah, this means disabling logging. The C library does not document `(ZooLogLevel)0` level, but it's actually worked. Maybe I should add a new `ZooLogSilence` level.

> state 999 (ZNOTCONNECTED_STATE) is not exposed by this API

`ZOO_NOTCONNECTED_STATE` is not exposed by zookeepe3.4 c client, but 3.6 does. I'll find a compatible way to add it later.

> exception handling model

All exceptions are under the [ZooKeeper.Exception](https://hackage.haskell.org/package/zoovisitor-0.2.5.1/docs/ZooKeeper-Exception.html) module. Like the [Exception from base library](https://hackage.haskell.org/package/base-4.18.0.0/docs/Control-Exception.html), exceptions are hierarchical. For example, creating an existing node should throw `ZNODEEXISTS`. You can catch either `ZNODEEXISTS` or all `ZooException`:

```
withResource client $ \zh -> void (zooCreate zh "/test" Nothing zooOpenAclUnsafe ZooPersistent) `catch` (\(e :: ZooException) -> print $ "Catch all ex: " <> show e)

withResource client $ \zh -> void (zooCreate zh "/test" Nothing zooOpenAclUnsafe ZooPersistent) `catch` (\(e :: ZNODEEXISTS) -> print $ "Catch only NodeExists: " <> show e)
```

Also, more examples are in the plan.

**Comment by 4eUeP** [comment]
@Dessix Hi, I have added a new function `withZooSetLogStream` to set log stream, does this solve your problem? Also, `ZOO_NOTCONNECTED_STATE` and `ZooLogSilence` is supported too. Any other questions or suggestions are welcome.

**Comment by Dessix** [comment]
Works for me ^^
